ENTER_NAME = 'Please enter your childs name: \n'
ENTER_FRIEND = 'Please enter your childs best friends name: \n'
ENTER_COLOR = 'Please choose your childs favorite colour:'
COLORS = ['blue', 'pink', 'yellow', 'orange']
ENTER_FOOD = 'Please enter your childs favourite food: \n'
ENTER_ANIMAL = 'Please enter your childs favourite animal: \n'
ENTER_SPORT = 'Please enter your childs favourite team sport: \n'
ENTER_DISLIKED_FOOD = 'Please enter a food your child does not like: \n'
ENTER_SEX = 'Is your child male or female? Please enter f\\m: \n'
SEX_OPTIONS = ('F', 'f', 'M', 'm')
CHOOSE_CHILD = 'Please choose the child the story should be personalized for: '
SELECT_NUMBER = 'Please select a number: \n'
NEW_STORY = 'Would you like to make a new story? Please enter yes\\no: \n'
YES_NO_OPTIONS = ('YES', 'Yes', 'yes', 'NO', 'No', 'no')
DELETE = 'Do you wish to delete your childs data? Please enter yes\\no: \n'
DELETE_CHILD = 'Please choose the child you wish to delete: '
ENTER_NUMBER = 'Enter a number: \n'
WELCOME = 'Welcome to Fairy Bot!\n'
NO_DELETE = 'There are no more children to delete.'
THANK_YOU = 'Thank you for using the Fairy Bot app. If you want to restart it,\
 press the Run Fairy Bot button.'